# Generated by Django 4.2.2 on 2023-06-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('femele', 'Femele')], max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('title_name', models.CharField(blank=True, max_length=255)),
                ('number_location', models.IntegerField(blank=True)),
                ('name_location', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('postcode', models.IntegerField(blank=True)),
                ('latitude', models.CharField(blank=True, max_length=100)),
                ('longitude', models.CharField(blank=True, max_length=100)),
                ('offset', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('uuid', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('salt', models.CharField(blank=True, max_length=255)),
                ('md5', models.CharField(blank=True, max_length=255)),
                ('sha1', models.CharField(blank=True, max_length=255)),
                ('sha256', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(blank=True)),
                ('age', models.IntegerField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('cell', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
