# Generated by Django 4.2.2 on 2023-06-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postcode',
            field=models.CharField(blank=True),
        ),
    ]
